### ISSUE TITLE
error in setNotifyValueForCharacteristic

### ISSUE THREAD

**Issue by lukaszspaczynski** [jordanebelanger/SwiftyBluetooth#1]
`public func setNotifyValueForCharacteristic(enabled: Bool,
                                                characteristicUUID: CBUUIDConvertible,
                                                serviceUUID: CBUUIDConvertible,
                                                completion: UpdateNotificationStateCallback)
    {
        self.peripheralProxy.setNotifyValueForCharacteristic(enabled,
                                                             characteristicUUID: characteristicUUID.CBUUIDRepresentation,
                                                             serviceUUID: characteristicUUID.CBUUIDRepresentation,
                                                             completion: completion)
    }`

wrong:

`serviceUUID: characteristicUUID.CBUUIDRepresentation`

should be:

`serviceUUID: serviceUUID.CBUUIDRepresentation`

**Comment by jordanebelanger** [comment]
@szpako1

Thank you for the issue report, this should be fixed in 0.1.1
https://github.com/tehjord/SwiftyBluetooth/commit/87fcae2e561f93e8fb31f7b491f9f93714320c5a

Also, how has the library been going for you so far, did you have a chance to play around with it a bit?
