### ISSUE TITLE
Xcode 8 integration

### ISSUE THREAD

**Issue by lukaszspaczynski** [jordanebelanger/SwiftyBluetooth#2]
Can't compile under Xcode 8. Conversion to swift 2.3 or 3.0 is needed.

**Comment by jordanebelanger** [comment]
50 errors anddddd dropping :) Swift 3 a real pain in the butt. 

I'll have to make the swift 3 branch the v2.0 of the library once it's ready, so let me know if there are any other fix you would like to see while we're at it.

**Comment by lukaszspaczynski** [comment]
@tehjord no other fixes are needed. Thanks for your job.

**Comment by lukaszspaczynski** [comment]
@tehjord hi, how about it?

**Comment by jordanebelanger** [comment]
@szpako1 Hi, currently working on it on and off, Swift3 notably require to do a pretty significant refactor of the internal Error enum, shouldnt take much longer hopefully.

**Comment by jordanebelanger** [comment]
@szpako1 Just released the first draft of the swift3 version, keep watching the swift3 branch for updates as I test it out and iron out bugs that might have been created during conversion.

I modified the public APIs to hopefully respect the Swift 3 api guidelines, currently trying to reduce the length of function names to be less verbose.

**Comment by lukaszspaczynski** [comment]
@tehjord Hi, I can't use that in my podspec file as dependency because podspec didn't have support for selecting branch / git path :|

When do you plan to marge swift3.0 branch to master?

**Comment by jordanebelanger** [comment]
Ah sorry about that, I didn't know you couldn't do that with Cocoapods, I've been using Carthage for sometimes now. Let me look into merging this thing today if I have time.

**Comment by jordanebelanger** [comment]
@szpako1 Alright I pushed the Swift 3 branch to master and updated the documentation + podspec repo. Enjoy!
