### ISSUE TITLE
Bluetooth Device writing error

### ISSUE THREAD

**Issue by sweetcodestar** [jordanebelanger/SwiftyBluetooth#33]
Hi @jordanebelanger 

Hope you are doing well. I am using your framework to write data to bluetooth device this is great framework for me.
This is the code to write data.
peripheral.writeValue(ofCharacWithUUID: authCharacteristic, fromServiceWithUUID: self.serviceUUID, value: keyBytes, completion: completion)
I am getting following error.
Error Domain=CBATTErrorDomain Code=132 "Unknown ATT error." UserInfo={NSLocalizedDescription=Unknown ATT error.}
I have checked the code carefully but I could not find the problem.
Can you please let me know how to write the data to bluetooth device?
Kind Regards.
Hua.

**Comment by jordanebelanger** [comment]
Interesting error, code 132 seem to be a weird one. 

Are you able to write to that device at all? Either on some other characteristic or by writing some other data?

**Comment by sweetcodestar** [comment]
Hi @jordanebelanger. Thank you for your reply.
I am able to write data for some characteristic. And I am not able to write several characteristic.
I am sorry I am new to bluetooth and fortunately I found this framework.
How can I write data to several characteristic?
Kind Regards.
Hua.

**Comment by jordanebelanger** [comment]
It seems like you're getting a GATT busy error from whatever device you're writing to, i.e a peripheral error. 

code 132 | 0x84 | GATT_BUSY

Check out https://www.google.com/search?client=safari&rls=en&q=gatt+busy+error&ie=UTF-8&oe=UTF-8

**Comment by sweetcodestar** [comment]
I checked the docs but could not find the solution.
I have two apps. One is from app store and it works well. It writes the data for any characteristic always.
Other one is mine that I am developing.
I just wanted to ask that there are any functions or notifications to unlock the bluetooth device.
Can you please let me know about this?
Kind Regards.
Hua.

**Comment by sweetcodestar** [comment]
Hi. It's was my mistake. Everything is working well. Thanks for your help.
