### ISSUE TITLE
I am getting service list nil, when i disconnect & connect again, with out killing the app.

### ISSUE THREAD

**Issue by ashokKOMARA** [jordanebelanger/SwiftyBluetooth#37]
I can able to get services list when i connect firs time with peripheral,then disconnected > connect again, now iam unable to list out any services.

**Comment by marcospolanco** [comment]
@ashokKOMARA I am having the exact same issue. Fix?

**Comment by ashokKOMARA** [comment]
No, but when i try to reconnect with same peripheral it is working fine. Some times when peripheral is connected in background it is returning the same nil.

**Comment by kshrikant** [comment]
Hey @ashokKOMARA , @marcospolanco anyone got the solution on this?

**Comment by kshrikant** [comment]
#12

**Comment by kshrikant** [comment]
Hi @ashokKOMARA , @marcospolanco @jordanebelanger Anyone know, how to resolve this  ?

**Comment by Dhaval3110** [comment]
Hello @kshrikant @ashokKOMARA @marcospolanco @jordanebelanger any update on this ? #39  check this also.

**Comment by jordanebelanger** [comment]
https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518706-discoverservices

"When the peripheral discovers one or more services, it calls the peripheral(_:didDiscoverServices:): method of its delegate object. After a peripheral discovers services, you can access them through the peripheral’s services property."
