### ISSUE TITLE
CBATTErrorDomain Code=2 "Reading is not permitted.

### ISSUE THREAD

**Issue by Muzammil-iOS** [jordanebelanger/SwiftyBluetooth#45]
When I read values  periperal.readValue(ofCharac: char, completion: { result in 

I am getting this error please help.

**Comment by ivan1997mxd** [comment]
I got same error
Error Domain=CBATTErrorDomain Code=2 "Reading is not permitted." UserInfo={NSLocalizedDescription=Reading is not permitted.}

**Comment by jordanebelanger** [comment]
Have you considered that this is because the characteristic you're trying to read is not readable?
