### ISSUE TITLE
How to get the state when the peripheral is disconnected?

### ISSUE THREAD

**Issue by mmswide** [jordanebelanger/SwiftyBluetooth#47]
func centralManager(_ central: CBCentralManager, didConnect peripheral: CBPeripheral)
I need to get this callback when the peripheral is disconnected.
How can I get this to work?
Many thanks.

**Comment by mmswide** [comment]
I will use original CBCentralDelegate and CBPeripheralDelegate.

**Comment by jordanebelanger** [comment]
@mobileguru121 If you want, I believe there is an NSNotification you can listen for. Check the interface of the Peripheral class it should be there.

**Comment by mmswide** [comment]
Thank you, but I could not find it. I appreciate if you can teach me.

**Comment by jordanebelanger** [comment]
Sure, perhaps you are on an older version, this was recently added.

Make sure to update to the latest version and check out https://github.com/jordanebelanger/SwiftyBluetooth/blob/65e47a63740254738d4262e2ee214cdff366c8c2/Sources/Peripheral.swift#L77

**Comment by mmswide** [comment]
Ok, thank you. I have to update the pod version to latest.

**Comment by mobileguru121** [comment]
Can you let me know the latest pod version?
I installed 5.0 but I can't find.
