### ISSUE TITLE
Xcode 13.1, v3.0.0 unhandled file warning

### ISSUE THREAD

**Issue by roberthartman** [jordanebelanger/SwiftyBluetooth#51]
After updating to Xcode 13.1 and SwiftBluetooth 3.0.0, included via Swift Package Manager, I now see the following warning:
![image](https://user-images.githubusercontent.com/4998988/143269715-1bed75ad-e790-4cb0-a720-3c279ba63f3f.png)

```
found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Users/rob.hartman/Library/Developer/Xcode/DerivedData/iOS_Example-cvpcvvkpubwmmuebviedncjenzcp/SourcePackages/checkouts/SwiftyBluetooth/Sources/Info.plist
```

One solution might be to modify `Package.swift` targets array, exluding that file:
```targets: [
        .target(name: "SwiftyBluetooth", path: "Sources", exclude: [Sources/Info.plist"])
    ]
```

**Comment by jordanebelanger** [comment]
@roberthartman Should be fixed in https://github.com/jordanebelanger/SwiftyBluetooth/releases/tag/3.0.1 thanks for reporting 👍

**Comment by roberthartman** [comment]
Thanks for the library!
