### ISSUE TITLE
Discovering Services doesn’t work as of iOS 15.4 Beta 

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [jordanebelanger/SwiftyBluetooth#53]
Discovering Services via .discoverServices doesn’t work anymore. Closure always results in failure.
Code is valid. (Even created a separate app to test this issue using THE SAME example code from readme)

Weird bug. Please fix (Can’t get back to using the default core bluetooth implementation after having used this blessing of a package)

**Comment by jordanebelanger** [comment]
Re-open once ios 15.4 is out of beta if it still happens...

Also try scanning and discovering services with a different phone/test devices and see if it also happens there.
